### ISSUE TITLE
recurrenced the code

### ISSUE THREAD

**Issue by LTNdeep** [monjurulkarim/DSTA#2]
I want to recurrence the code in the CUDA=11.1 environment.  I used the officialIs pretrained model weights for  demo.  But the result is incorrect.  it because of the environment？
![1](https://user-images.githubusercontent.com/42141135/177569590-49f77478-e9a9-4a3f-abc7-beb50285a26f.png)

**Comment by monjurulkarim** [comment]
@LTNdeep Hello, environment doesn't seem to be a problem. 
Since your result is on CCD dataset. Please refer to this 
https://github.com/Cogito2012/UString/issues/23#issuecomment-1166599523
