### ISSUE TITLE
Question about the Test

### ISSUE THREAD

**Issue by andrewwang0612** [monjurulkarim/DSTA#3]
Hello，Thanks for the amazing project!

I want to ask the test on accdient dataset.
If I want to get the value of each frame to compute AP and mtta，
how to sample the video frame and put it to the model to get the predict value?

Thanks for helping!

**Comment by monjurulkarim** [comment]
Greetings! Thank you for taking a look at our repository. To obtain the prediction probability of each video frame, you can execute the `demo.py` file. By doing so, the input video sequence will be processed, and the results for all frames will be stored in a numpy array.

https://github.com/monjurulkarim/DSTA/blob/8fc2ea39136d97128cb889b551b2dea0f19ffe35/demo.py#L301

**Comment by andrewwang0612** [comment]
Ok,I will check it.
Thank you so much!
