### ISSUE TITLE
Training on own dataset

### ISSUE THREAD

**Issue by 1211186431** [monjurulkarim/DSTA#4]
Hello, I want to replace the dad dataset with my personal dataset. There are a few questions that I hope you can answer.
1.What is `data['labels']` in `DADDataset`？
2.What is `data['ID']` in `DADDataset`？What is `data['labels']` in `DADDataset`？

**Comment by monjurulkarim** [comment]
Hello, thanks for checking out our repository.
Below are the information that you asked:
`labels`: One-hot video labels to indicate whether the video contains an accident, i.e., [0, 1] denotes positive (accident) and [1, 0] denotes negative (normal).
`ID`: The video name for current feature file.
